"""removed owners table

Revision ID: 901bf3901e90
Revises: f9c2ade5e02b
Create Date: 2023-04-05 07:07:17.943524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901bf3901e90'
down_revision = 'f9c2ade5e02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
